name: self-hosted-runner-demo
on:
  push:
    branches:
      - dev
jobs:
    demo-1:
      name: Demo Job 1
      runs-on: ubuntu-latest
      #runs-on: arc-runner-set
      steps:
        - name: Display system information
          run: |
            echo "Hostname: $(hostname)"
            echo "OS Version:"
            lsb_release -a || cat /etc/os-release
            echo "Runner Name: ${{ runner.name }}"
            echo "Runner OS: ${{ runner.os }}"
            #sleep 90
    demo-2:
      name: Demo job 2
      runs-on: ubuntu-latest
      #runs-on: arc-runner-set
      steps:
        - name: Display system information
          run: |
            echo "Hostname: $(hostname)"
            echo "OS Version:"
            lsb_release -a || cat /etc/os-release
            echo "Runner Name: ${{ runner.name }}"
            echo "Runner OS: ${{ runner.os }}"
#            sleep 90
